services:
  db:
    image: postgres:17
    container_name: 'save_data_container'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5435"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  web:
    build:
      context: .
    image: promo-image
    volumes:
      - .:/app
      - ./static:/static/
      - ./media:/media/
    env_file:
      - .env
    container_name: web-container
    command: gunicorn --workers=3 --timeout 300 --bind 0.0.0.0:8005 core.wsgi:application
    ports:
      - "8005:8005"
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL: postgres://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME

  bot:
    build:
      context: .
    image: bot-image
    volumes:
      - .:/app
    env_file:
      - .env
    container_name: bot-container
    command: python manage.py runbot
    restart: always


volumes:
  postgres_data:
  static:
  media:
