# Generated by Django 5.2.5 on 2025-08-23 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='x_api_key',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramusersubscribed',
            name='telegram_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed', to='common.telegramuser'),
        ),
    ]
