# Generated by Django 5.2.5 on 2025-08-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_telegramuser_x_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='common.telegramuser'),
        ),
    ]
