# Generated by Django 5.2.5 on 2025-08-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusersubscribed',
            name='is_subscribed',
        ),
    ]
