# Generated by Django 5.2.5 on 2025-09-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_telegramusersubscribed_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
