# Generated by Django 5.2.5 on 2025-09-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_paymentcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_subscription_price', models.IntegerField(default=30000)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentcheck',
            name='amount',
        ),
    ]
