# Generated by Django 5.2.5 on 2025-09-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_mainsettings_remove_paymentcheck_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='admin',
            field=models.CharField(default='abbosxon_toychiboyev', max_length=255),
        ),
    ]
