# Generated by Django 5.2.5 on 2025-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_mainsettings_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='card_holder',
            field=models.CharField(default='Abbosxon Toychiboyev', max_length=255),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='card_number',
            field=models.CharField(default='8600 1234 5678 9012', max_length=255),
        ),
    ]
